# Generated by Django 5.0.3 on 2024-03-27 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFiscales',
            fields=[
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre o Razon social(empresas)')),
                ('ape_pat', models.CharField(blank=True, max_length=100, verbose_name='Apellido paterno')),
                ('ape_mat', models.CharField(blank=True, max_length=100, verbose_name='Apellido materno')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('num_ext', models.CharField(max_length=100, verbose_name='Numero exterior')),
                ('num_int', models.CharField(blank=True, max_length=100, verbose_name='Numero interior')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio o alcadía')),
                ('cp', models.CharField(max_length=100, verbose_name='Código postal')),
                ('estado', models.CharField(choices=[('AG', 'Aguascalientes'), ('BC', 'Baja California'), ('BS', 'Baja California Sur'), ('CM', 'Campeche'), ('CS', 'Chiapas'), ('CH', 'Chihuahua'), ('CO', 'Coahuila'), ('CL', 'Colima'), ('DF', 'Ciudad de Mexico'), ('DG', 'Durango'), ('GT', 'Guanajuato'), ('GR', 'Guerrero'), ('HG', 'Hidalgo'), ('JA', 'Jalisco'), ('MX', 'Mexico'), ('MI', 'Michoacan'), ('MO', 'Morelos'), ('NA', 'Nayarit'), ('NL', 'Nuevo Leon'), ('OA', 'Oaxaca'), ('PU', 'Puebla'), ('QT', 'Queretaro'), ('QR', 'Quintana Roo'), ('SL', 'San Luis Potosi'), ('SI', 'Sinaloa'), ('SO', 'Sonora'), ('TB', 'Tabasco'), ('TM', 'Tamaulipas'), ('TL', 'Tlaxcala'), ('VE', 'Veracruz'), ('YU', 'Yucatan'), ('ZA', 'Zacatecas')], max_length=40, verbose_name='Estado')),
                ('telefono', models.CharField(max_length=30, verbose_name='Numero teléfonico')),
                ('rfc', models.CharField(max_length=30)),
                ('es_empresa', models.BooleanField(default=False, help_text='Las empresas son personas morales', verbose_name='Persona moral')),
                ('verificador_foto', models.ImageField(blank=True, upload_to='verificaciones', verbose_name='Foto de encierro de verificador')),
                ('verificador_direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección del domicilio fiscal')),
                ('es_verificado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos fiscales',
                'verbose_name_plural': 'Datos fiscales',
            },
        ),
    ]
