# Generated by Django 5.0.3 on 2024-04-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_transportista_encierro_unidades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='transportista',
            name='slug',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True),
        ),
    ]
