# Generated by Django 5.0.3 on 2024-05-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cliente_direccion_google'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosfiscales',
            name='verificador_direccion',
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='direccion_google',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
