# Generated by Django 5.0.3 on 2024-05-25 06:07

import django.db.models.deletion
import shared.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportistas',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('foto_perfil', models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Foto de perfil')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre o Razón Social')),
                ('ape_pat', models.CharField(blank=True, default='', max_length=100, verbose_name='Apellido paterno')),
                ('ape_mat', models.CharField(blank=True, default='', max_length=100, verbose_name='Apellido materno')),
                ('telefono', models.CharField(max_length=10, validators=[shared.validators.phone_validator], verbose_name='Número telefónico')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('num_ext', models.CharField(max_length=100, verbose_name='Número exterior')),
                ('num_int', models.CharField(blank=True, max_length=100, verbose_name='Número interior')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('cp', models.CharField(max_length=5, validators=[shared.validators.cp_validator], verbose_name='Código postal')),
                ('estado', models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Coahuila de Zaragoza', 'Coahuila de Zaragoza'), ('Colima', 'Colima'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('CDMX', 'CDMX'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('México', 'México'), ('Michoacán de Ocampo', 'Michoacán de Ocampo'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz de Ignacio de la Llave', 'Veracruz de Ignacio de la Llave'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=40, verbose_name='Estado')),
                ('calificacion', models.IntegerField(default=5, verbose_name='Calificación')),
                ('viajes_realizados', models.IntegerField(default=0, verbose_name='Viajes realizados')),
                ('notificacion_administrador', models.TextField(blank=True, verbose_name='Notificaciones para el transportista')),
                ('es_verificado', models.BooleanField(default=False)),
                ('direccion_google', models.CharField(blank=True, max_length=200)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('modificado_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
            },
        ),
        migrations.CreateModel(
            name='LicenciasTransportistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_licencia', models.CharField(choices=[('Licencia conducir', 'Licencia conducir'), ('Licencia material peligroso', 'Licencia material peligroso')], max_length=50, verbose_name='Tipo de licencia')),
                ('licencia', models.CharField(max_length=50, unique=True, verbose_name='Número de licencia')),
                ('fecha_vencimiento', models.DateTimeField(verbose_name='Fecha de vencimiento de la licencia')),
                ('licencia_foto', models.ImageField(upload_to='licencias_transportistas', verbose_name='Foto de licencia')),
                ('verificada', models.BooleanField(default=False)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('modificado_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportistas.transportistas')),
            ],
            options={
                'verbose_name': 'Licencia de transportista',
                'verbose_name_plural': 'Licencias de transportistas',
            },
        ),
        migrations.CreateModel(
            name='Encierros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de encierro')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('num_ext', models.CharField(max_length=100, verbose_name='Número exterior')),
                ('num_int', models.CharField(blank=True, max_length=100, verbose_name='Número interior')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio o alcaldía')),
                ('cp', models.CharField(max_length=6, validators=[shared.validators.cp_validator], verbose_name='Código postal')),
                ('estado', models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Coahuila de Zaragoza', 'Coahuila de Zaragoza'), ('Colima', 'Colima'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('CDMX', 'CDMX'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('México', 'México'), ('Michoacán de Ocampo', 'Michoacán de Ocampo'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz de Ignacio de la Llave', 'Veracruz de Ignacio de la Llave'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=40, verbose_name='Estado')),
                ('es_validado', models.BooleanField(default=False, verbose_name='Es válidado por administrador')),
                ('es_verificado', models.BooleanField(default=False)),
                ('es_activo', models.BooleanField(default=False)),
                ('direccion_google', models.CharField(blank=True, max_length=200, verbose_name='Dirección generado por Google Maps Api')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('modificado_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportistas.transportistas')),
            ],
            options={
                'verbose_name': 'Encierro',
                'verbose_name_plural': 'Encierros',
            },
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('año', models.IntegerField(choices=[(1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2024, verbose_name='Año')),
                ('tipo_caja', models.CharField(max_length=50, verbose_name='Tipo de caja')),
                ('capacidad_carga', models.FloatField(verbose_name='Capacidad de carga (toneladas)')),
                ('placa', models.CharField(max_length=15, unique=True, verbose_name='Placa')),
                ('tarjeta_circulacion', models.CharField(max_length=50, unique=True, verbose_name='Tarjeta de circulación')),
                ('tarjeta_circulacion_foto', models.ImageField(blank=True, null=True, upload_to='tarjetas_circulacion', verbose_name='Foto de tarjeta de circulación')),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='unidades_pics', verbose_name='Foto 1 de unidad')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='unidades_pics', verbose_name='Foto 2 de unidad')),
                ('es_verificado', models.BooleanField(default=False, verbose_name='Unidad verificada')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('modificado_at', models.DateTimeField(auto_now=True)),
                ('encierro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportistas.encierros')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportistas.transportistas')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
    ]
