# Generated by Django 5.0.3 on 2024-05-30 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre para identificar domicilio')),
                ('calle', models.CharField(max_length=200, verbose_name='Calle')),
                ('num_ext', models.CharField(max_length=200, verbose_name='Numero exterior')),
                ('num_int', models.CharField(blank=True, max_length=200, verbose_name='Numero interior')),
                ('colonia', models.CharField(max_length=200, verbose_name='Colonia')),
                ('municipio', models.CharField(max_length=200, verbose_name='Municipio o alcadía')),
                ('cp', models.CharField(max_length=200, verbose_name='Código postal')),
                ('estado', models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Coahuila de Zaragoza', 'Coahuila de Zaragoza'), ('Colima', 'Colima'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('CDMX', 'CDMX'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('México', 'México'), ('Michoacán de Ocampo', 'Michoacán de Ocampo'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz de Ignacio de la Llave', 'Veracruz de Ignacio de la Llave'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=100, verbose_name='Estado')),
                ('referencias', models.TextField(verbose_name='Refrencias del domicilio')),
                ('longitud', models.FloatField(blank=True, verbose_name='Longitud')),
                ('latitud', models.FloatField(blank=True, verbose_name='Latitud')),
                ('es_valida', models.BooleanField(default=False, verbose_name='Es válido')),
                ('formato_google', models.CharField(blank=True, max_length=200, verbose_name='Dirección completa')),
                ('id_google', models.CharField(blank=True, max_length=250, verbose_name='Google place ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('modificado_at', models.DateTimeField(auto_now=True)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
            options={
                'verbose_name_plural': 'Domicilios',
            },
        ),
    ]
