# Generated by Django 5.0.3 on 2024-05-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_domicilios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domicilios',
            old_name='cliente_id',
            new_name='user',
        ),
    ]
